//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Bad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bad()
        {
            this.Container = new HashSet<Container>();
        }
    
        public int BadID { get; set; }
        public string BLNumber { get; set; }
        public Nullable<System.DateTime> DateEmission { get; set; }
        public Nullable<System.DateTime> DateValidite { get; set; }
        public string CustomerNinea { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhoneNumber { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerAddress { get; set; }
        public byte[] PDF { get; set; }
        public string ShipperName { get; set; }
        public string ShipperAddress { get; set; }
        public string ConsigneeName { get; set; }
        public string ConsigneeAddress { get; set; }
        public string NotifyParty { get; set; }
        public Nullable<int> VoyageID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Voyage Voyage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Container> Container { get; set; }
        public int CountContainer { get; set; }

        public HttpPostedFileBase PdfFile { get; set; }

    }
}
