//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voyage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voyage()
        {
            this.Bad = new HashSet<Bad>();
        }
    
        public int VoyageID { get; set; }
        public Nullable<int> ShippingLineID { get; set; }
        public Nullable<int> PortOfLoading { get; set; }
        public Nullable<int> PortOfDischarge { get; set; }
        public Nullable<int> PortOfFinalPlaceOfDevlivery { get; set; }
        public Nullable<int> PortOfRecept { get; set; }
        public string VesselName { get; set; }
        public string VoyageNumber { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bad> Bad { get; set; }
        public virtual Port Port { get; set; }
        public virtual Port Port1 { get; set; }
        public virtual Port Port2 { get; set; }
        public virtual Port Port3 { get; set; }
        public virtual ShippingLine ShippingLine { get; set; }
        public int CountBad { get; set; }
    }
}
